### ISSUE TITLE
Administration / Namespaces on 4.9.0: Oh no! Something went wrong.

### ISSUE THREAD

**Issue by zigmund** [openshift/console#10522]
Hi there.

Console 4.9.0 on vanilla Kubernetes failed to render namespaces page with message "Oh no! Something went wrong.". 4.8 don't have such problem.

Component trace:
```
at U (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:520696)
    at div
    at N (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1035092)
    at m.memo.t.children.e.children.t.reduxes.e.reduxes.t.reduxes.every.reduxID (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:539684)
    at O (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:118:78241)
    at <anonymous> (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:541353)
    at O (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:118:78241)
    at div
    at <anonymous> (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1035800)
    at O (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:118:78241)
    at P (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1039983)
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1038395
    at o (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:215703)
    at ListPage
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:576030
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1380112
    at c (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:259809)
    at div
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:556912
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:454630
    at O (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:118:78241)
    at O (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:118:78241)
    at t (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:42:255755)
    at t (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:42:257798)
    at Suspense
    at div
    at div
    at section
    at p (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:226:173166)
    at t.a (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1490472)
    at div
    at div
    at c (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:221:349494)
    at u (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:178:113496)
    at div
    at u (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:78:22923)
    at l (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1191340)
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:514383
    at O (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:118:78241)
    at main
    at div
    at y (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:117:39676)
    at div
    at div
    at c (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:226:169644)
    at div
    at div
    at c (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:221:349494)
    at u (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:178:113496)
    at div
    at u (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:78:22923)
    at fn (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:42:164502)
    at t.a (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1016236)
    at t.default (https://console-domain/console-prefix/static/quick-start-chunk-04ba246cbf4014337b2e.min.js:1:1214)
    at c (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:259809)
    at t.a (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1569629)
    at z (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1571091)
    at Qe (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:42:128411)
    at z (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1571091)
    at z (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1571091)
    at t.a (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1566625)
    at l (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1563979)
    at Q (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1571221)
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1573937
    at r (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:179:423511)
    at t (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:42:255755)
    at t (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:42:257798)
    at t (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:42:252362)
    at Z (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:1574218)
    at t.a (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:837301)
    at t.a (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:179:413864)
    at Suspense
```

Stack trace:
```
TypeError: Cannot read properties of undefined (reading 'openshift.io/requester')
    at reducer (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:569583)
    at t.a (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:221:72324)
    at Object.a (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:93:159789)
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:521616
    at Array.map (<anonymous>)
    at https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:521485
    at Array.map (<anonymous>)
    at U (https://console-domain/console-prefix/static/main-chunk-53a6d779f7c9f45a272f.min.js:1:521429)
    at ea (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:249:58875)
    at zs (https://console-domain/console-prefix/static/vendors~main-chunk-21e2c293421176368fdb.min.js:249:111305)
```

**Comment by spadgett** [comment]
/cc @kdoberst 
/kind bug

It looks like we assume there are annotations on the namespace, and it's not always true.

**Comment by spadgett** [comment]
/assign @jhadvig 

@jhadvig Do you mind opening a Bugzilla bug for this issue?

**Comment by jerolimov** [comment]
Hello @zigmund, sorry for the delay, and thanks for your patient. I will take a look.

**Comment by jerolimov** [comment]
Hello @zigmund,

sorry for the delay, and thanks for your patience.

I could reproduce the error on 4.9-4.11 and can confirm that it doesn't happen in 4.8 and that it's already fixed on the master branch. We fixed this with PR #11791. I started a backport for 4.11 as well.

Do you need this for a specific release/branch or does a fix in 4.11 works fine in your case?

**Comment by zigmund** [comment]
Hey @jerolimov, thank you.

It will be fine, I'll upgrade our installation.

**Comment by TheRealJon** [comment]
Closing, as this has been resolved.
