### ISSUE TITLE
TypeError when navigating to Topology Tab in Developer mode (Chrome 101)

### ISSUE THREAD

**Issue by nccr-tobi** [openshift/console#11560]
Using Red Hat OpenShift Container Platform with Kubernetes version v1.23.3+e419edf

I am experiencing the following Error when navigating to the Topology Tab:

### Description:
Cannot destructure property 'kind' of 'undefined' as it is undefined.

### Component trace:
```
at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1575575)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1574447)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:923579)
    at t.a (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:276173)
    at div
    at h1
    at div
    at t.a (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:275630)
    at div
    at t.a (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:272408)
    at u (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:271050)
    at div
    at div
    at u (https://console-openshift-console.apps.<redacted>/static/2-chunk-847da2bf22fd171be117.min.js:26:297610)
    at div
    at div
    at p (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:76730)
    at t.a (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:278431)
    at div
    at c (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:501467)
    at d (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:80399)
    at div
    at d (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:603442)
    at div
    at div
    at c (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:734610)
    at div
    at c (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:82588)
    at div
    at https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:246728
    at S (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:93:81479)
    at t (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:118:37725)
    at https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:245979
    at https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:150:422900
    at div
    at _ (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:160398)
    at N (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:160846)
    at f (https://console-openshift-console.apps.<redacted>/static/2-chunk-847da2bf22fd171be117.min.js:26:14132)
    at https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:243233
    at https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:458353
    at S (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:93:81479)
    at div
    at div
    at t.b (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:86642)
    at t.a (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:110442)
    at u (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1058586)
    at https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:243582
    at o (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:235559)
    at withFallback()
    at t.default (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:13567)
    at s (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:297301)
    at t (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:21:58473)
    at j
    at t (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:21:60518)
    at Suspense
    at section
    at f (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:43758)
    at div
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1628607)
    at div
    at div
    at c (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:501467)
    at d (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:80399)
    at div
    at d (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:603442)
    at l (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1279637)
    at https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:550767
    at S (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:93:81479)
    at main
    at div
    at O (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:741428)
    at div
    at div
    at c (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:167229)
    at div
    at div
    at c (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:501467)
    at d (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:80399)
    at div
    at d (https://console-openshift-console.apps.<redacted>/static/vendor-patternfly-core-chunk-be485c76f11419b565cf.min.js:1:603442)
    at hn (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:36:181594)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1121717)
    at t.default (https://console-openshift-console.apps.<redacted>/static/quick-start-chunk-abc53ff9330681668b86.min.js:1:1223)
    at s (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:297301)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1701898)
    at Q (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1717247)
    at et (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:36:143623)
    at Q (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1717247)
    at Q (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1717247)
    at Q (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1717247)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1697601)
    at c (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1695004)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1697412)
    at J (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1717377)
    at https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1720136
    at r (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:36:119264)
    at t (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:21:58473)
    at t (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:21:60518)
    at t (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:21:55078)
    at X (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1720482)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:922385)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:864576)
    at t.a (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:150:413803)
    at Suspense
```
### Stack trace:
```
TypeError: Cannot destructure property 'kind' of 'undefined' as it is undefined.
    at h (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:207248)
    at p (https://console-openshift-console.apps.<redacted>/static/dev-console-topology-chunk-dd48a4017921bd906cac.min.js:1:3257)
    at t.a (https://console-openshift-console.apps.<redacted>/static/main-chunk-bfb7e1eba91c17ab329d.min.js:1:1575635)
    at na (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:263:58879)
    at Hs (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:263:111315)
    at xc (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:263:98327)
    at Cc (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:263:98255)
    at _c (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:263:98118)
    at pc (https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:263:95105)
    at https://console-openshift-console.apps.<redacted>/static/vendors~main-chunk-ef6e956a76c708c2f12e.min.js:263:44774
 ```

> Question: How can I give more information, so you can debug and maybe even reproduce this?

In the Browser Developer Console Network Tab I see at least 5 requests answering with 403 Forbidden HTTP Errors on fetch GET requests to 
- /api/kubernetes/apis/ocs.openshift.io/v1/namespaces/openshift-storage/storageclusters?
- /api/kubernetes/api/v1/namespaces/openshift-storage
- /api/kubernetes/apis/ceph.rook.io/v1/namespaces/openshift-storage/cephclusters?
- /api/kubernetes/apis/noobaa.io/v1alpha1/namespaces/openshift-storage/noobaas?

This might be unrelated, but probably leads to a variable named kind with an undefined state when the fetch function returns an error.

**Comment by nccr-tobi** [comment]
This apparently only happens with Chrome (tested with version 101.0.4951.41), so it may be a bundling compatibility issue.

Brave Browser (Version 1.39.111 Chromium: 102.0.5005.61) does not throw this error.
