### ISSUE TITLE
Javascript error when trying to view standalone pod.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/console#1259]
In OpenShift 4.0 deployed using try.openshift.com, if you have a standalone pod which wasn't created by a deployment, deployment config etc, but was created by a custom application directly using REST API, when trying to view that pod in the web console pods view, you get a Javascript error when rendering the page.

```
TypeError
Description:
Cannot read property 'reduce' of undefined

Component Trace:
in T
    in div
    in I
    in e
    in e
    in div
    in k
    in StatusBox
    in div
    in div
    in t
    in div
    in Unknown
    in Connect(Component)
    in t
    in Connect(t)
    in Unknown
    in div
    in t
    in DetailsPage
    in PodsDetailsPage
    in t
    in Unknown
    in ResourceDetailsPage
    in e
    in e
    in div
    in div
    in section
    in h
    in main
    in div
    in p
    in t
    in e
    in e
    in o

Stack Trace:
TypeError: Cannot read property 'reduce' of undefined
    at f (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/main-chunk-91d2e2911d575cc81f92.min.js:1:512617)
    at T (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/main-chunk-91d2e2911d575cc81f92.min.js:1:220964)
    at beginWork (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:50239)
    at o (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:54823)
    at a (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:55102)
    at C (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:58045)
    at _ (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:57588)
    at b (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:57425)
    at m (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:56804)
    at p (https://console-openshift-console.apps.try0.tectonic.joshix.com/static/vendors~main-chunk-f8130edc1af37e48f7c7.min.js:107:56266)
```

Have also seen this issue when console image was deployed direct into a 3.11 cluster as well.

Console URL path was:

```
/k8s/ns/jupyter/pods/jupyterhub-nb-e7026b5c-2d4b8b-2d46be-2da9ce-2d74ee069dcd9e
```

**Comment by spadgett** [comment]
@GrahamDumpleton Are you able to share the YAML for the pod?

**Comment by GrahamDumpleton** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    hub.jupyter.org/username: 8gkfb
    openshift.io/scc: anyuid
  creationTimestamp: 2019-03-14T23:08:02Z
  labels:
    app: fossasia
    component: singleuser-server
    hub: fossasia-workshop
    user: 8gkfb
  name: fossasia-workshop-8gkfb
  namespace: workshop
  resourceVersion: "921771"
  selfLink: /api/v1/namespaces/workshop/pods/fossasia-workshop-8gkfb
  uid: 04b34089-46ae-11e9-8602-001e67978cbf
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - /usr/libexec/s2i/run
    - --ip="0.0.0.0"
    - --port=10080
    env:
    - name: JUPYTERHUB_ROUTE
      value: https://fossasia-workshop.apps.xxx.io
    - name: CLUSTER_SUBDOMAIN
      value: apps.xxx.io
    - name: CONSOLE_URL
      value: http://localhost:10083
    - name: RESTART_URL
      value: /restart
    - name: JUPYTERHUB_API_TOKEN
      value: xxx
    - name: JPY_API_TOKEN
      value: xxx
    - name: JUPYTERHUB_ADMIN_ACCESS
      value: "1"
    - name: JUPYTERHUB_CLIENT_ID
      value: jupyterhub-user-8gkfb
    - name: JUPYTERHUB_HOST
    - name: JUPYTERHUB_OAUTH_CALLBACK_URL
      value: /user/8gkfb/oauth_callback
    - name: JUPYTERHUB_USER
      value: 8gkfb
    - name: JUPYTERHUB_API_URL
      value: http://fossasia:8081/hub/api
    - name: JUPYTERHUB_BASE_URL
      value: /
    - name: JUPYTERHUB_SERVICE_PREFIX
      value: /user/8gkfb/
    - name: MEM_LIMIT
      value: "536870912"
    - name: JUPYTER_IMAGE_SPEC
      value: docker-registry.default.svc:5000/workshop/fossasia-app:latest
    - name: JUPYTER_IMAGE
      value: docker-registry.default.svc:5000/workshop/fossasia-app:latest
    - name: PROJECT_NAMESPACE
      value: fossasia-workshop-8gkfb
    - name: JUPYTERHUB_NAMESPACE
      value: workshop
    - name: JUPYTERHUB_APPLICATION
      value: fossasia
    - name: HOMEROOM_LINK
      value: https://homeroom-workshop.apps.xxx.io/
    image: docker-registry.default.svc:5000/workshop/fossasia-app@sha256:03d32cc2566af3b310dcb450a1c89f74d1e5cdc618d1095d4fe1802dde4887ca
    imagePullPolicy: Always
    lifecycle: {}
    name: notebook
    ports:
    - containerPort: 10080
      name: notebook-port
      protocol: TCP
    resources:
      limits:
        memory: "536870912"
      requests:
        memory: "536870912"
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fossasia-workshop-8gkfb-token-kkj44
      readOnly: true
  - command:
    - /opt/bridge/bin/bridge
    env:
    - name: BRIDGE_K8S_MODE
      value: in-cluster
    - name: BRIDGE_LISTEN
      value: http://0.0.0.0:10083
    - name: BRIDGE_BASE_ADDRESS
      value: https://fossasia-workshop.apps.xxx.io/
    - name: BRIDGE_BASE_PATH
      value: /user/8gkfb/console/
    - name: BRIDGE_PUBLIC_DIR
      value: /opt/bridge/static
    - name: BRIDGE_USER_AUTH
      value: disabled
    image: quay.io/openshift/origin-console:latest
    imagePullPolicy: Always
    name: console
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fossasia-workshop-8gkfb-token-kkj44
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: fossasia-workshop-8gkfb-dockercfg-xb575
  nodeName: localhost.localdomain
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000080000
    runAsUser: 1000080000
    seLinuxOptions:
      level: s0:c9,c4
  serviceAccount: fossasia-workshop-8gkfb
  serviceAccountName: fossasia-workshop-8gkfb
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: fossasia-workshop-8gkfb-token-kkj44
    secret:
      defaultMode: 420
      secretName: fossasia-workshop-8gkfb-token-kkj44
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-03-14T23:08:02Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-03-14T23:08:18Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2019-03-14T23:08:02Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://00bbbde9a7fbc62c3788ae210ecc135fa4a04cf4d765a02989cbdbc1de19ff2f
    image: quay.io/openshift/origin-console:latest
    imageID: docker-pullable://quay.io/openshift/origin-console@sha256:630ef041345061d0d94d75c744c01a1449508a7ea72f03a80a4637ff08372806
    lastState: {}
    name: console
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-03-14T23:08:18Z
  - containerID: docker://b25ad902905c6a3af6db03f742c5566773d079dfccf24a596a351b90f2b76452
    image: docker-registry.default.svc:5000/workshop/lab-kubernetes-fundamentals:latest
    imageID: docker-pullable://docker-registry.default.svc:5000/workshop/fossasia-app@sha256:03d32cc2566af3b310dcb450a1c89f74d1e5cdc618d1095d4fe1802dde4887ca
    lastState: {}
    name: notebook
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-03-14T23:08:14Z
  hostIP: 192.168.0.25
  phase: Running
  podIP: 10.128.1.110
  qosClass: Burstable
  startTime: 2019-03-14T23:08:02Z
```

**Comment by spadgett** [comment]
Hey @GrahamDumpleton. I haven't been able to reproduce this unfortunately even with the YAML. Are you still seeing this with newer builds?

**Comment by spadgett** [comment]
We haven't been able to reproduce even with the provided YAML. Closing for now. If you see this with current builds, please let us know.

/close
