### ISSUE TITLE
okd-console-Virtualizaton-overview:Oh no! Something went wrong.

### ISSUE THREAD

**Issue by pdo2013** [openshift/console#13351]
oc version :4.14.0-0.okd-2023-11-14-101924
os version :fedora-coreos-38.20230609.3.0-live.x86_64

Error on okd console virtualization tab,after install kubevirt:
```

TypeError
Description:
(0 , _openshift_console_dynamic_plugin_sdk_internal__WEBPACK_IMPORTED_MODULE_5__.useActiveNamespace) is not a function or its return value is not iterable

Component trace:
at VMsPerTemplateCard (https://console-openshift-console.apps.example.com/api/plugins/kubevirt-plugin/exposed-ClusterOverviewPage-chunk.js:6371:119)
    at div
    at u (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:88227)
    at div
    at u (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:159561)
    at div
    at t.default (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:229160)
    at OverviewTab
    at i (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:320100)
    at t (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:21:69882)
    at t (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:21:71963)
    at Suspense
    at div
    at https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:768695
    at T (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:771696)
    at ClusterOverviewPage (https://console-openshift-console.apps.example.com/api/plugins/kubevirt-plugin/exposed-ClusterOverviewPage-chunk.js:3269:119)
    at t (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:21:69882)
    at A (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1273780)
    at t (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:21:71963)
    at Suspense
    at i (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:320100)
    at section
    at m (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:246503)
    at div
    at div
    at t.a (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1274009)
    at div
    at div
    at l (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:732088)
    at d (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:297176)
    at div
    at d (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:151344)
    at c (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1039797)
    at https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:294354
    at x (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:116:86676)
    at main
    at div
    at v (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:529360)
    at div
    at div
    at l (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:382824)
    at div
    at div
    at l (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:732088)
    at d (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:297176)
    at div
    at d (https://console-openshift-console.apps.example.com/static/vendor-patternfly-core-chunk-f9a774f4908f2be047b1.min.js:1:151344)
    at Jn (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:58:172658)
    at t.default (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:789911)
    at e.default (https://console-openshift-console.apps.example.com/static/quick-start-chunk-db41ca4b544990b88d16.min.js:1:3537)
    at s (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:150012)
    at t.a (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1350800)
    at ee (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1370786)
    at xt (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:58:129794)
    at ee (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1370786)
    at ee (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1370786)
    at ee (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1370786)
    at ModalProvider (https://console-openshift-console.apps.example.com/api/plugins/kubevirt-plugin/exposed-modalProvider-chunk.js:44:26)
    at ee (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1370786)
    at ee (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1370786)
    at o (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:732612)
    at t.a (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1343220)
    at t.a (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1343409)
    at t.a (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1340895)
    at te (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1370908)
    at ne (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1372926)
    at t (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:21:69882)
    at t (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:21:71963)
    at P (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:58:4488)
    at ne (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:58:9932)
    at te (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:58:9341)
    at X (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:115:11631)
    at t (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:21:66312)
    at ae (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:1373188)
    at t.a (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:706876)
    at t.a (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:959902)
    at s (https://console-openshift-console.apps.example.com/static/main-chunk-4360858a39805f47818a.min.js:1:510668)
    at t.a (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:168:195071)
    at Suspense

Stack trace:

TypeError: (0 , _openshift_console_dynamic_plugin_sdk_internal__WEBPACK_IMPORTED_MODULE_5__.useActiveNamespace) is not a function or its return value is not iterable
    at useVMsPerTemplateResources (https://console-openshift-console.apps.example.com/api/plugins/kubevirt-plugin/exposed-ClusterOverviewPage-chunk.js:6436:129)
    at VMsPerTemplateCard (https://console-openshift-console.apps.example.com/api/plugins/kubevirt-plugin/exposed-ClusterOverviewPage-chunk.js:6372:117)
    at na (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:281:58879)
    at Hs (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:281:111315)
    at Su (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:281:98327)
    at Cu (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:281:98255)
    at _u (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:281:98118)
    at pu (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:281:95105)
    at https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:281:44774
    at t.unstable_runWithPriority (https://console-openshift-console.apps.example.com/static/vendors~main-chunk-e203dccdf92baa489a3e.min.js:289:3768)
```

How to fix this?

**Comment by huangyan20** [comment]
I also encountered the same problem in CRC
