### ISSUE TITLE
Viewing "All Instances" of operator throws js error

### ISSUE THREAD

**Issue by thomasmckay** [openshift/console#8211]
https://issues.redhat.com/browse/PROJQUAY-1636

OCP 4.6.16
Red Hat Quay operator

```
TypeError: Cannot read property 'reduce' of null
    at https://console-openshift-console.apps.thomasmckay.quayteam.org/static/main-chunk-7ce6ad496de46fac272c.min.js:1:665073
    at No (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:55337)
    at Ks (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:98261)
    at Bs (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:84008)
    at Fs (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:81035)
    at Ms (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:79608)
    at https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:41759
    at t.unstable_runWithPriority (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:183:3878)
    at li (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:41488)
    at hi (https://console-openshift-console.apps.thomasmckay.quayteam.org/static/vendors~main-chunk-097f186a6bd6062a5833.min.js:175:41705)
```

**Comment by TheRealJon** [comment]
Reproduced and opened a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1937018
